import { glob, rm } from "@goodbyenjn/utils/fs";
import { defineConfig } from "rolldown";

import packageJson from "./package.json";

const isWatchMode = process.env["ROLLDOWN_WATCH"] === "true";
const { version, description, author, obsidian } = packageJson;
const { id, name, isDesktopOnly, minAppVersion } = obsidian;
const manifest = JSON.stringify(
    {
        id: id + (isWatchMode ? "-dev" : ""),
        name: name + (isWatchMode ? " (Dev)" : ""),
        version,
        author: author.name,
        authorUrl: author.url,
        description,
        isDesktopOnly,
        minAppVersion,
    } satisfies Manifest,
    null,
    4,
);

export default defineConfig({
    input: ["src/main.ts", "src/styles.css"],

    output: {
        dir: "dist",
        format: "cjs",
        minify: true,
    },

    external: ["obsidian", "electron"],

    moduleTypes: {},
    transform: {
        define: {
            "process.env.MANIFEST": manifest,
        },
    },

    plugins: [
        {
            name: "plugin:cleanup",
            async generateBundle(options) {
                const dir = options.dir!;
                const files = await glob("*", {
                    cwd: dir,
                    ignore: "data.json",
                    dot: true,
                    absolute: true,
                });
                await Promise.all(files.map(file => rm(file)));
            },
        },
        {
            name: "plugin:assets",
            async generateBundle(_, bundle) {
                // Remove the styles.js file generated by the styles.css entry point, since the CSS support in Rolldown is currently imcomplete.
                // https://github.com/rolldown/rolldown/issues/4271
                delete bundle["styles.js"];

                this.emitFile({
                    type: "asset",
                    fileName: "manifest.json",
                    source: manifest,
                });

                if (isWatchMode) {
                    this.emitFile({
                        type: "asset",
                        fileName: ".hotreload",
                        source: "",
                    });
                }
            },
        },
    ],
});
